### ISSUE TITLE
Cmd class requires explicit public initializer 

### ISSUE THREAD

**Issue by W-Lawless** [michaelvanstraten/swifty-redis#1]
Cmd is unusable outside the package as `init` lacks an explicit `public` access level, see: 

https://stackoverflow.com/questions/40249531/why-does-a-public-class-struct-in-swift-require-an-explicit-public-initializer/40251059

**Comment by michaelvanstraten** [comment]
Foremost, thank you for creating an issue.

This is my first swift package, so I am new to the whole publication process. While developing, I ran into the issue that I could not find a way to test public facing code, so I would just rely on unit tests to check if the interface was working as intended. Maybe you know a way to test public facing code in Swift, so that this does not happen again.

I will fix the issue in a sec

**Comment by W-Lawless** [comment]
You're welcome bud, and moreso thank you for writing the package! It is by far much more usable than some of the other solutions; which either are very complex using odd EventLoop strategies instead of sockets, or which are easy enough to use, but give you back awful NS types and wrap ObjC methods. 

Your package is great because it is easy to use, and easy to deserialize the types properly

**Comment by W-Lawless** [comment]
Btw; your package is featured on the official redis site; 

https://redis.io/resources/clients/
