### ISSUE TITLE
Docs could be improved 

### ISSUE THREAD

**Issue by W-Lawless** [michaelvanstraten/swifty-redis#2]
Your README file doesn't include `.query` method on the end of the `connection.get` example; the expression doesn't return the proper type without it

**Comment by michaelvanstraten** [comment]
Okay, here is the problem: 
should you have to call `.query()` or `.exec()` on command, or should the just always call `.query()` for you?

On the one side you have one function call less to worry about, on the other side are you more flexible with your return value.

Since I could not decide on which to choose, i kind of gave up on that question until there was some interest on this package, so I could get some input from others. That's why I did not update the docs. So what do you think is more viable?

I lean more towards the commands already calling `.query()` for simplicity’s sake.

**Comment by W-Lawless** [comment]
Personally I like having the choice between either query or exec, as I might want to call exec for something like subscribe, where I don't really care about the return value, and query elsewhere
